# Generated by Django 4.2.2 on 2023-06-24 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/images/"),
        ),
        migrations.CreateModel(
            name="Food_Choise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_choise",
                        to="items.food",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_choise",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
